### ISSUE TITLE
Suggestion for the mod: weapon transmogrifier (cosmetic option)

### ISSUE THREAD

**Issue by davizon200** [Aurilux/Armiger#3]
Hello Aurilux!

Would love to see implemented in your mod an option to maybe transmogrify a weapon for example:

Have a diamond sword equipped but it looks like a wooden sword (still doing the diamond sword damage)

Another cool implementation could be a crafting bench type block where you can edit the colors of your weapons?

maybe for players to paint pixel by pixel?

dont know if this last thing is possible but im dropping here as a suggestion!

**Comment by Aurilux** [comment]
Closing this since it is currently outside the scope of this mod.
